spring:
  application:
    name: gateway-service-zuul
zuul:
  routes:
    api-a:
      path: /api1/**
      serviceId: eureka-producer
server:
  port: 10001
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8001/eureka/,http://peer1:8000/eureka/,http://peer3:8002/eureka/