spring:
  application:
    name: gateway-service-zuul
  zipkin:
    base-url: http://localhost:8888
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    api-a:
      path: ${api1.path}
      serviceId: ${api1.serviceId}
server:
  port: 10001