spring:
  application:
    name: config-repository
  profiles:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/0jas0/config-test-repository
          search-paths: eureka-server
server:
  port: 10000
eureka:
  client:
    serviceUrl:
      #defaultZone: http://peer2:8001/eureka/,http://peer1:8000/eureka/,http://peer3:8002/eureka/
      defaultZone: http://peer:8005/eureka/