spring:
  application:
    name: eureka-producer
server:
  port: 9000
eureka:
  client:
      serviceUrl:
        defaultZone: http://peer2:8001/eureka/,http://peer1:8000/eureka/,http://peer3:8002/eureka/