spring:
  application:
    name: eureka-producer
  zipkin:
      base-url: http://localhost:8888
  sleuth:
      sampler:
        percentage: 1.0
server:
  port: 9000
eureka:
  client:
      serviceUrl:
        #defaultZone: http://peer2:8001/eureka/,http://peer1:8000/eureka/,http://peer3:8002/eureka/
        defaultZone: http://peer:8005/eureka/