server:
  port: 8888
spring:
  application:
    name: zikpin-server
management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  client:
      serviceUrl:
        defaultZone: http://peer2:8001/eureka/,http://peer1:8000/eureka/,http://peer3:8002/eureka/