spring:
  application:
    name: eureka-server3
server:
  port: 8002
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      #defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
      defaultZone: ${defaultZone3}