spring:
  application:
    name: eureka-server
server:
  port: 8005
eureka:
  instance:
    hostname: peer
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false #表示是否从Eureka Server获取注册信息，默认为true
    register-with-eureka: false # 表示是否将自己注册到Eureka Server，默认为true。